### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by maccy10** [macmule/MapDrivesAndPrintersBasedOnADGroupMembershipOnOSX#1]
A Syntax Error is experienced when trying to compile the script 'as is' (i.e. direct copy and paste) in Script Editor. I've attached a screenshot for information. Currently using OS X 10.10.4.

![screen shot 2015-07-14 at 20 22 33](https://cloud.githubusercontent.com/assets/13338421/8682716/586417dc-2a66-11e5-8209-3a7929d7ceb4.png)

**Comment by maccy10** [comment]
Found the issue, 'set accountType.....' should be on a separate line.

**Comment by macmule** [comment]
ok thanks.. sorry for not responding!!
